---
- hosts: all
  tasks:
    - name: create directory 
      file: path=/var/log/Comandos/ state=directory
    - name: Ejecutar el comando export para ver fecha y hora
      command: echo "export HISTTIMEFORMAT='%F %T = '" >> $HOME/.bashrc
    - name: Crear carpeta de log
      file: path=/var/log/Comandos/$USER.log state=touch
    - name: Ejecutar comando history
      command: history > $USER.log
