---
- hosts: all
  vars:
    users:
      - username: "mariano"
        groups: "mariano,sudo"
        shell: "/bin/bash"
        password: "mariano"
      - username: "jesus"
        groups: "jesus,sudo"
        shell: "/bin/bash"
        password: "jesus"
    group:
      - group: "mariano"
      - group: "sudo"
      - group: "jesus"
        
  tasks:
  - name: create groups 
    group: 
      name: "{{ item.group }}"
    with_items: 
      "{{ group }}"
    
  - name: create users with groups, shell and password.
    user:
      name: "{{ item.username }}"
      groups: "{{ item.groups }}"
      shell: "{{ item.shell }}"
      password: "{{ item.password }}"
    with_items:
      "{{ users }}"
