---
- hosts: all
  become: true
  gather_facts: false
  vars:
    users:
      - username: mariano
      - groups: mariano,sudo
      - shell: /bin/bash
      - password: mariano

  tasks:
  - name: create users with groups, shell and password.
    user:
      name: {{ item.username }}
      groups: {{ item.groups }}
      shell: {{ item.shell }}
      password: {{ item.password }}
    with_items: {{ users }}
