---
- hosts: all
  tasks:
    - name: Disable Root Login
      lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line="PermitRootLogin no" state=present
      
    handlers:
      - name: Restart SSH service.
        service: name=sshd state=restarted
