---
- hosts: all
  tasks:
    - name: create group
      group: name=bernal 
    - name: create user
      user: name=bernal group=bernal shell=/bin/bass password="{{ 'bernal' | password_hash('sha512') }}"
